machine:
  php:
    version: 7.0.7
    
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker 
      - image: circleci/php:7.3-stretch-node-browsers
    steps:
      - checkout
      

dependencies:
  cache_directories:
    - vendor
  override:
    - composer install

test:
  override:
    - php vendor/bin/phpunit --testsuit Unit

general:
  branches:
    only:
      - master
